Repository owncloud/ios-app, pull requests merged in 2018-08, with the labels that each got.

#102 Feature/rename
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/NamingViewController.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/SDK Extensions/OCItem+Extension.swift
  ownCloud/Theming/NSObject+ThemeApplication.swift
Labels: Approved by QA, feature: file operation, feature:fileList

#96 Extend UI tests for passcode feature
  Podfile.lock
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Settings/SecuritySettingsSection.swift
  ownCloudTests/Security/PasscodeTests.swift
Labels: QA

#105 Add UI tests on biometrical lock
  ownCloud/Settings/SecuritySettingsSection.swift
  ownCloudTests/Security/BiometricalTests.swift
Labels: QA

#108 Fix for the app crash when bookmark is deleted
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Server List/ServerListTableViewController.swift
Labels: Approved by QA

#107 Fix/sortbar hidden when no items
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/SortBar.swift
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA
