Repository owncloud/ios-app, pull requests merged in 2018-10, with the labels that each got.

#124 Fix TVG rendering
  img/filetypes-tvg/application-pdf.tvg
  img/filetypes-tvg/application.tvg
  img/filetypes-tvg/audio.tvg
  img/filetypes-tvg/file.tvg
  img/filetypes-tvg/folder-create.tvg
  img/filetypes-tvg/folder-drag-accept.tvg
  img/filetypes-tvg/folder-external.tvg
  img/filetypes-tvg/folder-public.tvg
  img/filetypes-tvg/folder-shared.tvg
  img/filetypes-tvg/folder-starred.tvg
  img/filetypes-tvg/folder.tvg
  img/filetypes-tvg/icon-locked.tvg
  img/filetypes-tvg/icon-password-manager.tvg
  img/filetypes-tvg/image.tvg
  img/filetypes-tvg/owncloud-logo.tvg
  img/filetypes-tvg/package-x-generic.tvg
  img/filetypes-tvg/text-calendar.tvg
  img/filetypes-tvg/text-code.tvg
  img/filetypes-tvg/text-vcard.tvg
  img/filetypes-tvg/text.tvg
  img/filetypes-tvg/video.tvg
  img/filetypes-tvg/x-office-document.tvg
  img/filetypes-tvg/x-office-presentation.tvg
  img/filetypes-tvg/x-office-spreadsheet.tvg
  ownCloud/Theming/TVG/TVGImage.swift
  tools/MakeTVG/main.swift
Labels: Approved by QA

#131 Feature/previewer refinements
  ownCloud/UI Elements/ImageScrollView.swift
  ownCloud/Viewer/DisplayHostViewController.swift
  ownCloud/Viewer/ImageDisplayViewController.swift
Labels: Approved by QA, enhancement

#128 Add Fastlane .env changes
  .gitignore
  fastlane/Appfile
  fastlane/Appfile.sample
  fastlane/Matchfile
  fastlane/Matchfile.sample
Labels: enhancement, p2-high
