Repository owncloud/ios-app, pull requests merged in 2018-11, with the labels that each got.

#138 First implementation of PDF viewer feature
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Resources/Assets.xcassets/ic_pdf_go_to_page.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/ic_pdf_go_to_page.imageset/ic_open_in_new_24px.pdf
  ownCloud/Resources/Assets.xcassets/ic_pdf_outline.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/ic_pdf_outline.imageset/ic_list_24px.pdf
  ownCloud/Resources/Assets.xcassets/ic_pdf_view_multipage.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/ic_pdf_view_multipage.imageset/ic_border_all_24px.pdf
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Theming/NSObject+ThemeApplication.swift
  ownCloud/UIKit Extensions/String+Extension.swift
  ownCloud/Viewer/PDFOutlineViewController.swift
  ownCloud/Viewer/PDFSearchTableViewCell.swift
  ownCloud/Viewer/PDFSearchViewController.swift
  ownCloud/Viewer/PDFThumbnailCollectionViewCell.swift
  ownCloud/Viewer/PDFThumbnailsCollectionViewController.swift
  ownCloud/Viewer/PDFTocItem.swift
  ownCloud/Viewer/PDFTocTableViewCell.swift
  ownCloud/Viewer/PDFTocTableViewController.swift
  ownCloud/Viewer/PDFViewerViewController.swift
Labels: Approved by QA, p2-high

#156 Fix for imageScrollView center function.
  ownCloud/UI Elements/ImageScrollView.swift
Labels: bug, p2-high

#162 [fix/memoryleaks] Fix memory leaks / retain cycles
  ownCloud/UI Elements/Card Presentation Controller/CardTransitionDelegate.swift
Labels: p2-high
