Repository owncloud/ios-app, pull requests merged in 2019-03, with the labels that each got.

#296 #294 added missing view controller title for "Lock application"
  ownCloud/Settings/SecuritySettingsSection.swift
Labels: Approved by QA

#289 #288 fixed large title snaps, instead of smooth scrolling
  ownCloud/UI Elements/StaticTableViewController.swift
Labels: Approved by QA, Design

#284 #283 Fixed Localization in code and localizable.strings
  .gitattributes
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/Action.swift
  ownCloud/Client/Actions/Actions+Extensions/CreateFolderAction.swift
  ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
  ownCloud/Resources/cs.lproj/Localizable.strings
  ownCloud/Resources/de-DE.lproj/Localizable.strings
  ownCloud/Resources/de.lproj/Localizable.strings
  ownCloud/Resources/en-GB.lproj/Localizable.strings
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Resources/pt-BR.lproj/Localizable.strings
  ownCloud/Resources/pt-PT.lproj/Localizable.strings
  ownCloud/Resources/ru.lproj/Localizable.strings
  ownCloud/Resources/sq.lproj/Localizable.strings
  ownCloud/Resources/th-TH.lproj/Localizable.strings
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Settings/LogSettingsViewController.swift
  ownCloud/Settings/SecuritySettingsSection.swift
  ownCloud/Theming/ThemeStyle+DefaultStyles.swift
Labels: Approved by QA

#295 Multiple upload from photo album
  design/camera_badge.sketch/Data
  design/camera_badge.sketch/QuickLook/Preview.png
  design/camera_badge.sketch/QuickLook/Thumbnail.png
  design/camera_badge.sketch/metadata
  design/camera_badge.sketch/version
  design/checkmark_Icon.sketch/Data
  design/checkmark_Icon.sketch/QuickLook/Preview.png
  design/checkmark_Icon.sketch/QuickLook/Thumbnail.png
  design/checkmark_Icon.sketch/metadata
  design/checkmark_Icon.sketch/version
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/PhotoAlbumTableViewCell.swift
  ownCloud/Client/PhotoAlbumTableViewController.swift
  ownCloud/Client/PhotoSelectionViewCell.swift
  ownCloud/Client/PhotoSelectionViewController.swift
  ownCloud/Resources/Assets.xcassets/camera-badge.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/camera-badge.imageset/camera-badge.pdf
  ownCloud/Resources/Assets.xcassets/check-mark.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/check-mark.imageset/checkmark.pdf
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA, feature:uploads, p3-medium

#300 Last item was overlapped by Tab bar
  ownCloud/Client/ClientQueryViewController.swift
Labels: Approved by QA, Design, bug

#299 Activated the Gather coverage to all targets
  ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloudTests.xcscheme
Labels: Approved by QA

#308 Changed full width button to a rounded button
  ownCloud/Server List/ServerListTableViewController.xib
  ownCloud/Settings/Passcode/PasscodeViewController.swift
  ownCloud/Settings/Passcode/PasscodeViewController.xib
Labels: Approved by QA

#277 Gallery of images
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/Gallery/GalleryHostViewController.swift
  ownCloud/UI Elements/ImageScrollView.swift
  ownCloud/UIKit Extensions/String+Extension.swift
  ownCloud/Viewer/DisplayViewController.swift
  ownCloud/Viewer/ImageDisplayViewController.swift
  ownCloud/Viewer/WebViewDisplayViewController.swift
Labels: Approved by QA

#307 Display view: use complete screen height
  ownCloud/Viewer/DisplayHostViewController.swift
Labels: Approved by QA

#312 Added keyboard field navigation for username, password textfield in bookmark view
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Resources/Assets.xcassets/arrow-down.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/arrow-down.imageset/down 2.pdf
  ownCloud/Resources/Assets.xcassets/arrow-up.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/arrow-up.imageset/up 2.pdf
  ownCloud/Resources/Assets.xcassets/check-mark.imageset/checkmark.pdf
Labels: Approved by QA, Estimation - 3 (M)

#333 Fixed TextField UI
  ownCloud/Client/Actions/NamingViewController.swift
Labels: Approved by QA, Design

#318 Inter-App drag and drop, Toolbar actions for drag and drop
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Resources/Assets.xcassets/folder.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/folder.imageset/folder.pdf
  ownCloud/Resources/Assets.xcassets/trash.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/trash.imageset/trash-25.pdf
  ownCloud/UIKit Extensions/UIBarButtonItem+Extension.swift
  ownCloud/UIKit Extensions/UIButton+Extension.swift
Labels: Approved by QA

#332 Fixed missing check-mark images (multiple upload)
  ownCloud/Resources/Assets.xcassets/check-mark.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/check-mark.imageset/checkmark.pdf
Labels: Approved by QA, Design, bug
