Repository owncloud/ios-app, pull requests merged in 2019-04, with the labels that each got.

#344 Generate IPA for Bitrise test builds
  fastlane/Fastfile
  fastlane/README.md
Labels: Approved by QA, Estimation - 3 (M)

#336 Fixed Width for Progress View when Downloading a File
  ownCloud/UI Elements/DownloadFileProgressHUDViewController.swift
Labels: Approved by QA

#339 Add test to cover latest UI changes in authentication flow
  ownCloudTests/Login/CreateBookmarkTests.swift
  ownCloudTests/Login/EditBookmarkTests.swift
  ownCloudTests/Tools/UtilsTests.swift
Labels: Automatic testing, Estimation - 3 (M)

#348 Correct handling for duplicated file names
  fastlane/Fastfile
  ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
  ownCloud/Resources/de-DE.lproj/Localizable.strings
  ownCloud/Resources/de.lproj/Localizable.strings
  ownCloud/Resources/en-GB.lproj/Localizable.strings
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Tools/DispatchQueueTools.swift
  ownCloud/UIKit Extensions/String+Extension.swift
  ownCloudTests/Login/CreateBookmarkTests.swift
  ownCloudTests/Login/EditBookmarkTests.swift
Labels: Approved by QA, feature: file operation

#350 [fix/gallery-view] Fix double-download issue in Gallery View
  ownCloud/Gallery/GalleryHostViewController.swift
Labels: p2-high

#363 Feature/heic to jpeg
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/Actions+Extensions/UploadPhotosAction.swift
  ownCloud/Resources/de-DE.lproj/Localizable.strings
  ownCloud/Resources/de.lproj/Localizable.strings
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Resources/ru.lproj/Localizable.strings
  ownCloud/Settings/PhotoUploadSection.swift
  ownCloud/Settings/SettingsViewController.swift
Labels: Approved by QA
