Repository owncloud/ios-app, pull requests merged in 2019-10, with the labels that each got.

#517 [fix/filename-truncate-tail] Truncate middle of file name instead of tail
  ownCloud/Client/ClientItemCell.swift
Labels: Approved by QA

#523 Fixed mission icons for ‘moreFolder’ location
  ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UnshareAction.swift
Labels: Estimation - 1 (XS), bug

#498 [feature/multiple-windows] Multiple window support for iPadOS
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Actions+Extensions/DiscardSceneAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenSceneAction.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/FileLists/FileListTableViewController.swift
  ownCloud/FileLists/QueryFileListTableViewController.swift
  ownCloud/Resources/Info.plist
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/SDK Extensions/OCCore+Extension.swift
  ownCloud/SDK Extensions/OCItem+Extension.swift
  ownCloud/SceneDelegate.swift
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Tools/VendorServices.swift
  ownCloud/Window/OpenItemUserActivity.swift
Labels: Approved by QA, iOS 13

#494 [feature/docs] Docs support
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Scanner/FixedHeightImageView.swift
  ownCloud/Client/Actions/Scanner/ScanAction.swift
  ownCloud/Client/Actions/Scanner/ScanViewController.swift
  ownCloud/Resources/Info.plist
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/UI Elements/StaticTableViewRow.swift
  ownCloudAppFramework/Tools/NSData+Encoding.h
  ownCloudAppFramework/Tools/NSData+Encoding.m
  ownCloudAppFramework/ownCloudApp.h
Labels: Approved by QA, iOS 13
