Repository owncloud/ios-app, pull requests merged in 2019-05, with the labels that each got.

#355 UI for navigating between folders in current path
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/BreadCrumbTableViewController.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/UI Elements/StaticTableViewRow.swift
Labels: Approved by QA, Estimation - 2 (S), feature:fileList

#371 Added support for additional mime-types
  ownCloud/Viewer/WebViewDisplayViewController.swift
Labels: Approved by QA

#297 UI tests on "Settings"
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Settings/MoreSettingsSection.swift
  ownCloud/Settings/UserInterfaceSettingsSection.swift
  ownCloudTests/Security/PasscodeTests.swift
  ownCloudTests/SettingsTests.swift
Labels: Automatic testing

#366 Not showing empty folder message on copy / move
  ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
  ownCloud/Client/ClientItemCell.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Settings/SettingsViewController.swift
Labels: Approved by QA, bug, p2-high

#388 Actionable navigation title
  ownCloud/Client/ClientQueryViewController.swift
Labels: Approved by QA
