Repository owncloud/ios-app, pull requests merged in 2019-02, with the labels that each got.

#239 Accessibility improvements
  .swiftlint.yml
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Client/Actions/NamingViewController.swift
  ownCloud/Client/ClientItemCell.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/SortBar.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Server List/ServerListBookmarkCell.swift
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Theming/NSObject+ThemeApplication.swift
  ownCloud/Theming/UI/ThemeButton.swift
  ownCloud/UI Elements/StaticTableViewRow.swift
  ownCloud/Viewer/DisplayViewController.swift
Labels: Approved by QA

#234 Multi selection on the file list
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
  ownCloud/Client/ClientItemCell.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/UIKit Extensions/UIBarButtonItem+Extension.swift
  ownCloud/UIKit Extensions/UIViewController+Extension.swift
Labels: Approved by QA, feature:fileList, p3-medium

#254 Clean up before release
  doc/CONFIGURATION.md
  ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Settings/MoreSettingsSection.swift
  ownCloud/Settings/SettingsViewController.swift
  ownCloud/Tools/VendorServices.swift
Labels: Approved by QA

#244 Launch Screen
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Resources/BackgroundImage.png
  ownCloud/Resources/Base.lproj/LaunchScreen.storyboard
  ownCloud/Resources/SplashImage.png
Labels: Approved by QA

#249 sever --> server
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA, Login, bug, p2-high

#259 Replace hardcoded "ownCloud" words with app specific name
  ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
  ownCloud/Server List/ServerListTableViewController.swift
Labels: Approved by QA

#263 Remove spaces from account@host in the bookmark list
  ownCloud/SDK Extensions/OCBookmark+Extension.swift
Labels: Approved by QA, enhancement, p2-high

#271 Change 'bookmark' with 'account'.
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Server List/ServerListTableViewController.xib
  ownCloudTests/Tools/OwnCloudTests.swift
Labels: Approved by QA

#262 StaticTableViewButtons corner radius
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Settings/Passcode/PasscodeViewController.swift
  ownCloud/Theming/UI/ThemeRoundedButton.swift
  ownCloud/UI Elements/StaticTableViewRow.swift
  ownCloudTests/Login/CreateBookmarkTests.swift
  ownCloudTests/Login/EditBookmarkTests.swift
Labels: Approved by QA, Design

#279 Added a Starting log on the init of every test in order to know which one was executed and the order to debug easily
  ownCloud.xcodeproj/project.pbxproj
  ownCloudTests/File List/FileListTests.swift
  ownCloudTests/Login/CreateBookmarkTests.swift
  ownCloudTests/Security/BiometricalTests.swift
  ownCloudTests/Security/PasscodeTests.swift
  ownCloudTests/Tools/XCTestsCase+Extension.swift
Labels: Approved by QA, Automatic testing

#280 Fixed wrong spacing for Sort menu in file list
  ownCloud/Client/SortBar.swift
Labels: Approved by QA, Design

#272 [MDM] Create a simple MDM/AppConfig/specfile.xml
  MDM/AppConfig/README.md
  MDM/AppConfig/minimal-specfile.xml
Labels: feature:MDM, p2-high
