Repository owncloud/ios-app, pull requests merged in 2019-08, with the labels that each got.

#464 [Earlgrey] Settings' suite expanded
  ownCloud/Settings/MediaUploadSettingsSection.swift
  ownCloudTests/SettingsTests.swift
Labels: Automatic testing

#471 [feature/bundle-import] Add support for certain bundle formats to the share sheet
  fastlane/Fastfile
  ownCloud File Provider/FileProviderExtension.m
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Actions+Extensions/UploadBaseAction.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Import/ImportFilesController.swift
  ownCloud/Resources/Info.plist
  ownCloudAppFramework/Display Settings/DisplaySettings.h
  ownCloudAppFramework/Display Settings/DisplaySettings.m
  ownCloudAppFramework/Resources/Info.plist
  ownCloudAppFramework/SDK Extensions/OCCore+BundleImport.h
  ownCloudAppFramework/SDK Extensions/OCCore+BundleImport.m
  ownCloudAppFramework/ZIP Archive/ZIPArchive.h
  ownCloudAppFramework/ZIP Archive/ZIPArchive.m
  ownCloudAppFramework/ownCloudApp.h
Labels: Approved by QA

#474 [feature/sort direction] Allow sorting asc/desc for all sort methods
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/Library/LibraryFilesTableViewController.swift
  ownCloud/Client/SortBar.swift
  ownCloud/Client/SortMethod.swift
  ownCloud/Client/SortMethodTableViewController.swift
  ownCloud/FileLists/QueryFileListTableViewController.swift
  ownCloud/Resources/Assets.xcassets/Image.imageset/Contents.json
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/UIKit Extensions/String+Extension.swift
Labels: Approved by QA, Estimation - 2 (S)

#469 [fix/index-bar] Make Index Bar available in general file list
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Library/LibraryFilesTableViewController.swift
  ownCloud/Client/Library/LibraryTableViewController.swift
  ownCloud/FileLists/QueryFileListTableViewController.swift
Labels: Approved by QA, Estimation - 1 (XS)

#476 Change behaviour of default expiration date
  ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
  ownCloud/UI Elements/StaticTableViewRow.swift
Labels: Approved by QA

#467 Permission increasing UX in reshares
  ownCloud/Client/Sharing/GroupSharingEditTableViewController.swift
  ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
  ownCloud/Client/Sharing/PublicLinkTableViewController.swift
Labels: Approved by QA, Design, enhancement

#478 [feature/reorder buttons] Reorder Navigation Bar Actions
  ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloud.xcscheme
  ownCloud.xcodeproj/xcshareddata/xcschemes/ownCloudTests.xcscheme
  ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeAvailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeUnavailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/SortBar.swift
  ownCloud/FileLists/QueryFileListTableViewController.swift
  ownCloud/Resources/Assets.xcassets/select.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/select.imageset/Selection.pdf
Labels: Approved by QA, Estimation - 2 (S)
