Repository owncloud/ios-app, pull requests merged in 2020-01, with the labels that each got.

#591 [fix/passcode] Fix iOS 13 passcode screen issue
  ownCloud/AppDelegate.swift
  ownCloud/SceneDelegate.swift
  ownCloud/Settings/Passcode/AppLockManager.swift
  ownCloud/Theming/UI/ThemeWindow.swift
Labels: Approved by QA, Estimation - 3 (M)

#593 [release/1.2.1] Release 1.2.1
  CHANGELOG.md
  ownCloud File Provider/Info.plist
  ownCloud File ProviderUI/Info.plist
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Resources/Info.plist
  ownCloud/SceneDelegate.swift
  ownCloud/Settings/Passcode/AppLockManager.swift
  ownCloud/Tasks/InstantMediaUploadTaskExtension.swift
  ownCloud/Theming/UI/ThemeWindow.swift
  ownCloudAppFramework/Resources/Info.plist
  ownCloudScreenshotsTests/Info.plist
  ownCloudTests/Info.plist
Labels: Approved by QA

#594 [feature/filelist-layout] Cleaner File List Layout
  ownCloud/Client/ClientItemCell.swift
  ownCloud/FileLists/FileListTableViewController.swift
  ownCloud/Resources/Assets.xcassets/more-dots.imageset/more-dots.png
  ownCloud/Resources/Assets.xcassets/more-dots.imageset/more-dots@2x.png
  ownCloud/Resources/Assets.xcassets/more-dots.imageset/more-dots@3x.png
Labels: Approved by QA, Estimation - 2 (S)

#596 [feature/directory-picker-sort-bar] Show Sort Bar in Directory Picker
  ownCloud/Client/Actions/ClientDirectoryPickerViewController.swift
Labels: Approved by QA

#599 Updated README.MD
  .gitignore
  README.md
  fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPad Pro (12.9-inch) (3rd generation)-60_ios_settings_demo.png
  fastlane/screenshots/en-US/iPhone 7-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPhone 7-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPhone 7-20_ios_files_list_demo.png
  fastlane/screenshots/en-US/iPhone 7-21_ios_files_actions_demo.png
  fastlane/screenshots/en-US/iPhone 7-22_ios_files_preview_pdf_demo.png
  fastlane/screenshots/en-US/iPhone 7-40_ios_quick_access_demo.png
  fastlane/screenshots/en-US/iPhone 7-60_ios_settings_demo.png
  fastlane/screenshots/en-US/iPhone 8 Plus-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPhone 8 Plus-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPhone 8 Plus-60_ios_settings_demo.png
  fastlane/screenshots/en-US/iPhone SE-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPhone SE-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPhone SE-60_ios_settings_demo.png
  fastlane/screenshots/en-US/iPhone X-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPhone X-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPhone X-60_ios_settings_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-10_ios_accounts_welcome_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-11_ios_accounts_list_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-20_ios_files_list_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-21_ios_files_actions_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-22_ios_files_preview_pdf_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-40_ios_quick_access_demo.png
  fastlane/screenshots/en-US/iPhone Xs Max-60_ios_settings_demo.png
  fastlane/screenshots/screenshots.html
Labels: Approved by QA

#551 Correct structure of templates to create issues of different kinds
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/ISSUE_TEMPLATE/release_template.md
Labels: Approved by QA, Estimation - 1 (XS)

#605 [fix/sharingview-ipad] Broken Sharing View on iPad
  ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
  ownCloud/Settings/LogFilesViewController.swift
Labels: Approved by QA, Estimation - 1 (XS)

#602 [fix/stucks-in-blank-view] UI Restoration bug > App unusable
  ownCloud/Client/ClientRootViewController.swift
Labels: Approved by QA, Estimation - 1 (XS)

#603 move PR template to .github
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/release_template.md
  .github/pull_request_template.md
Labels: Approved by QA, Estimation - 1 (XS)

#600 [feature/quick-access-collections ] Expand Quick Access Collections
  ownCloud/Client/Library/LibraryTableViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA, Estimation - 1 (XS)
