Repository owncloud/ios-app, pull requests merged in 2020-06, with the labels that each got.

#707 Take Photo or Video and Upload
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Actions+Extensions/UploadCameraMediaAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UploadMediaAction.swift
  ownCloud/Resources/Assets.xcassets/camera.imageset/Contents.json
  ownCloud/Resources/Assets.xcassets/camera.imageset/camera.pdf
  ownCloud/Resources/Info.plist
  ownCloud/Resources/en.lproj/InfoPlist.strings
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA, feature:uploads

#718 [feature/contextual-menu] Contextual Menu for File List Items
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/release_template.md
  docs/modules/ROOT/pages/ios_settings.adoc
  ownCloud/Client/Actions/Action.swift
  ownCloud/Client/Actions/Actions+Extensions/CollaborateAction.swift
  ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
  ownCloud/Client/Actions/Actions+Extensions/CreateFolderAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DiscardSceneAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DocumentEditingAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
  ownCloud/Client/Actions/Actions+Extensions/FavoriteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/LinksAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeAvailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeUnavailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MediaEditingAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenSceneAction.swift
  ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UnfavoriteAction.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA

#687 Support changing the format of uploaded image file names
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AVFoundation Extensions/AVAsset+Extension.swift
  ownCloud/Media Uploads/CoreImage Extensions/CIImage+Extensions.swift
  ownCloud/Media Uploads/MediaUploadActivity.swift
  ownCloud/Media Uploads/MediaUploadQueue.swift
  ownCloud/Media Uploads/MediaUploadStorage.swift
  ownCloud/Media Uploads/PhotoKit Extensions/PHAsset+Upload.swift
  ownCloud/Media Uploads/PhotoKit Extensions/PHPhotoLibrary+Extension.swift
  ownCloud/PhotoKit Extensions/PHAsset+Upload.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Settings/MediaUploadSettingsSection.swift
  ownCloud/Tools/URL+Extensions.swift
Labels: Approved by QA

#730 Fixes for markup and PDF viewer
  ownCloud/Client/Actions/EditDocumentViewController.swift
  ownCloud/Client/Viewer/DisplayViewController.swift
  ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
Labels: Approved by QA, bug, feature:previews

#728 Include new dialog to encourage users to add a new app review in App Store
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Actions+Extensions/UploadCameraMediaAction.swift
  ownCloud/Release Notes/ReleaseNotesHostViewController.swift
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Settings/SettingsViewController.swift
  ownCloud/Tasks/ScheduledTaskManager.swift
  ownCloud/Tools/VendorServices.swift
  ownCloudAppShared/Tools/AppStatistics.swift
  tools/MakeTVG/main.swift
Labels: Approved by QA, enhancement
