Repository owncloud/ios-app, pull requests merged in 2020-08, with the labels that each got.

#754 [fix/mime-type-uti] Added missing third party app UTIs
  ownCloud File Provider/OCItem+FileProviderItem.m
Labels: Approved by QA, Estimation - 1 (XS), bug

#768 [fix/quick-access-available-offline] Quick Access: Only show available offline items
  ownCloud/Client/Library/Item Policies/ItemPolicyTableViewController.swift
Labels: Approved by QA, bug

#771 [feature/selection-counter-label] File List: Selected items counter label
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/FileLists/QueryFileListTableViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
Labels: Approved by QA, Estimation - 1 (XS), feature:fileList

#781 [Docs] Add FAQ and improve navigation
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/ios_faq.adoc
  docs/modules/ROOT/pages/ios_settings.adoc
Labels: documentation

#764 Fixes improving performance during multiple selection
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UnshareAction.swift
  ownCloud/Client/FileList Extensions/QueryFileListTableViewController+Multiselect.swift
  ownCloud/Client/Viewer/DisplayExtension.swift
  ownCloud/Client/Viewer/Image/ImageDisplayViewController.swift
  ownCloud/Client/Viewer/QuickLook/PreviewViewController.swift
  ownCloud/Client/Viewer/WebView/WebViewDisplayViewController.swift
  ownCloudAppShared/Client/Actions/Action.swift
  ownCloudAppShared/Client/File Lists/ClientQueryViewController.swift
  ownCloudAppShared/Client/File Lists/QueryFileListTableViewController.swift
  ownCloudAppShared/SDK Extensions/OCItem+Extension.swift
  ownCloudTests/SettingsTests.swift
Labels: Approved by QA
