Repository owncloud/ios-app, pull requests merged in 2020-04, with the labels that each got.

#656 [feature/ipad-pointerinteraction] Implementation of iPad UIPointerInteraction to give the user a vi…
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Actions/MoreViewHeader.swift
  ownCloud/Client/ClientItemCell.swift
  ownCloud/Client/PhotoAlbumTableViewCell.swift
  ownCloud/Client/PhotoSelectionViewCell.swift
  ownCloud/Client/SortBar.swift
  ownCloud/Client/Viewer/DisplayViewController.swift
  ownCloud/Client/Viewer/PDF/PDFThumbnailCollectionViewCell.swift
  ownCloud/Server List/ServerListBookmarkCell.swift
  ownCloud/Settings/Passcode/PasscodeViewController.swift
  ownCloud/UI Elements/PointerEffect.swift
  ownCloud/UI Elements/StaticTableViewRow.swift
Labels: Approved by QA

#677 Update documentation to reflect changes in instant photo upload
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/ios_task_scheduling.adoc
Labels: documentation

#673 [feature/improve-public-link-creation] Improve creation of public link
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Client/Sharing/PublicLinkEditTableViewController.swift
  ownCloud/Client/Sharing/PublicLinkTableViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/UI Elements/NotificationHUDViewController.swift
  ownCloud/UI Elements/ProgressHUDViewController.swift
  ownCloud/UI Elements/StaticTableViewRow.swift
Labels: Approved by QA

#686 [fix/audio-stop-playing] Stop playing Audio when item loosing focus
  ownCloud/Client/Viewer/Media/MediaDisplayViewController.swift
Labels: Approved by QA, Estimation - 1 (XS), bug
