Repository owncloud/ios-app, pull requests merged in 2020-05, with the labels that each got.

#689 [fix/round-shape-button] Fix round shape for pin code buttons
  ownCloud/Licensing/Offers/LicenseOfferButton.swift
  ownCloud/Theming/UI/ThemeButton.swift
  ownCloud/Theming/UI/ThemeRoundedButton.swift
Labels: Approved by QA, Estimation - 1 (XS), bug

#690 [feature/resign-script] Resign Script
  enterprise/MDM/AppConfig/README.md
  enterprise/MDM/AppConfig/minimal-specfile.xml
  enterprise/MDM/AppConfig/specfile.xml
  enterprise/resign/App/ad-hoc/README.md
  enterprise/resign/App/app-store/README.md
  enterprise/resign/Provisioning Files/ad-hoc/README.md
  enterprise/resign/Provisioning Files/app-store/README.md
  enterprise/resign/README.md
  enterprise/resign/resignOwncloudApp
Labels: Estimation - 3 (M)

#701 Fixed some issues with VoiceOver / accessibility labels
  ownCloud/Client/Actions/MoreViewHeader.swift
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Client/SortBar.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/UI Elements/Card Presentation Controller/CardPresentationController.swift
Labels: Accessibility, Approved by QA

#666 Fix docs build errors
  docs/modules/ROOT/pages/ios_settings.adoc
Labels: bug, documentation
