Repository owncloud/ios-app, pull requests merged in 2020-11, with the labels that each got.

#818 [docs] Add Jamf Pro MDM example
  docs/modules/ROOT/pages/ios_mdm.adoc
Labels: documentation, feature:MDM

#834 [milestone/11.4.3] Milestone 11.4.3 (bugfixes)
  CHANGELOG.md
  fastlane/metadata-emm/en-US/release_notes.txt
  fastlane/metadata-owncloud-online/en-US/release_notes.txt
  fastlane/metadata/en-US/release_notes.txt
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/Release Notes/ReleaseNotes.plist
  ownCloudAppShared/Client/File Lists/ClientQueryViewController.swift
  ownCloudAppShared/Client/User Interface/SortBar.swift
  ownCloudAppShared/User Interface/StaticTableView/StaticTableViewRow.swift
Labels: Approved by QA

#839 [fix/fastlane-set-keychain-group] Set Keychain Group for all targets in Fastlane Builds
  fastlane/Fastfile
Labels: bug
