Repository owncloud/ios-app, pull requests merged in 2020-03, with the labels that each got.

#642 [fix/subscription-ui] Equalize subscription UI font size.
  ownCloud/Licensing/Offers/LicenseOfferView.swift
Labels: Approved by QA

#643 [feature/drag-drop-setting] Setting to disable dragging files inside the app
  ownCloud/Client/ClientQueryViewController.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Settings/DisplaySettingsSection.swift
  ownCloudAppFramework/Display Settings/DisplaySettings.h
  ownCloudAppFramework/Display Settings/DisplaySettings.m
  ownCloudTests/SettingsTests.swift
Labels: Approved by QA

#490 Update Antora/Documentation dependencies to the latest versions
  docs/yarn.lock
Labels: documentation, p3-medium

#528 Document new features in version 1.1.1
  docs/modules/ROOT/assets/images/21_File_list.png
  docs/modules/ROOT/assets/images/21_File_list_annotated.png
  docs/modules/ROOT/assets/images/21_File_list_parent.jpg
  docs/modules/ROOT/assets/images/21_File_list_parent.png
  docs/modules/ROOT/assets/images/directory-actions.png
  docs/modules/ROOT/assets/images/file-actions.jpg
  docs/modules/ROOT/assets/images/index-bar-with-callout.png
  docs/modules/ROOT/assets/images/index-bar.png
  docs/modules/ROOT/assets/images/sort-files-landscape-mode.png
  docs/modules/ROOT/assets/images/sort-files-portrait-mode.png
  docs/modules/ROOT/assets/images/themes/classic.png
  docs/modules/ROOT/assets/images/themes/dark.png
  docs/modules/ROOT/assets/images/themes/light.png
  docs/modules/ROOT/pages/ios_files.adoc
  docs/modules/ROOT/pages/ios_settings.adoc
Labels: documentation

#636 Document oauth2 app requirement for 2fa in the iOS app
  docs/modules/ROOT/pages/ios_accounts.adoc
Labels: documentation

#527 1928 document offline support
  docs/modules/ROOT/assets/images/offline-storage/all-available-offline-items.png
  docs/modules/ROOT/assets/images/offline-storage/available-offline-badge-closeup-with-callout.png
  docs/modules/ROOT/assets/images/offline-storage/available-offline-badge-closeup.png
  docs/modules/ROOT/assets/images/offline-storage/available-offline-badge.png
  docs/modules/ROOT/assets/images/offline-storage/available-offline-items.png
  docs/modules/ROOT/assets/images/offline-storage/available-offline-logo.png
  docs/modules/ROOT/assets/images/offline-storage/file-available-offline.png
  docs/modules/ROOT/assets/images/offline-storage/folder-action.png
  docs/modules/ROOT/assets/images/offline-storage/make-available-offline.png
  docs/modules/ROOT/assets/images/offline-storage/make-unavailable-offline.png
  docs/modules/ROOT/assets/images/offline-storage/not-available-offline-logo.png
  docs/modules/ROOT/assets/images/offline-storage/offline-storage-settings.png
  docs/modules/ROOT/assets/images/offline-storage/one-folder-available-offline.png
  docs/modules/ROOT/assets/images/offline-storage/quick-access-view-nothing-available-offline.png
  docs/modules/ROOT/assets/images/offline-storage/quick-access-view-toc.png
  docs/modules/ROOT/assets/images/offline-storage/regular-badges.png
  docs/modules/ROOT/assets/images/offline-storage/settings.png
  docs/modules/ROOT/assets/images/quick-access-view.png
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/ios_available_offline.adoc
  docs/modules/ROOT/pages/ios_files.adoc
  docs/modules/ROOT/pages/ios_quick_access.adoc
  docs/yarn.lock
Labels: documentation

#440 Replace the Documentation Makefile with a Shell Script
  docs/Makefile
  docs/bin/cli
  docs/books/ownCloud_iOS_App_Manual.adoc
Labels: documentation
