Repository owncloud/ios-app, pull requests merged in 2021-03, with the labels that each got.

#905 [fix/pdf-thumbnailview-position] PDF thumbnail view position on the iPad
  CHANGELOG.md
  changelog/unreleased/905
  ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
Labels: Approved by QA

#911 [fix/collapsible-progress-bar-position-flex] Collapse Progress Bar in Detail View
  CHANGELOG.md
  changelog/unreleased/906
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/UI Elements/CollapsibleProgressBar.swift
  ownCloudAppShared/User Interface/Progress/ProgressSummarizer.swift
Labels: Approved by QA

#913 Accessing hyper links in PDF view
  CHANGELOG.md
  changelog/unreleased/4432
  ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
Labels: bug

#920 [fix/auto-page-scrolling] Auto Enable Page Scrolling in Detail View
  CHANGELOG.md
  changelog/unreleased/918
  ownCloud/Client/Viewer/DisplayHostViewController.swift
Labels: Approved by QA

#922 [feature/align-bookmark-names] Align bookmark names with Android and web
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Server List/ServerListBookmarkCell.swift
  ownCloudAppFramework/SDK Extensions/OCBookmark+AppExtensions.m
Labels: Approved by QA

#893 [feature/prevent-sleep-detail-view] Presentation Mode
  CHANGELOG.md
  changelog/unreleased/704
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Client/Actions/Actions+Extensions/CopyAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DeleteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DisplayExifMetadataAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DocumentEditingAction.swift
  ownCloud/Client/Actions/Actions+Extensions/DuplicateAction.swift
  ownCloud/Client/Actions/Actions+Extensions/FavoriteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeAvailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MakeUnavailableOfflineAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MediaEditingAction.swift
  ownCloud/Client/Actions/Actions+Extensions/MoveAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenInAction.swift
  ownCloud/Client/Actions/Actions+Extensions/OpenSceneAction.swift
  ownCloud/Client/Actions/Actions+Extensions/PresentationModeAction.swift
  ownCloud/Client/Actions/Actions+Extensions/RenameAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UnfavoriteAction.swift
  ownCloud/Client/Actions/Actions+Extensions/UnshareAction.swift
  ownCloud/Client/Viewer/DisplayHostViewController.swift
  ownCloud/Client/Viewer/DisplayViewController.swift
  ownCloud/Client/Viewer/Image/ImageDisplayViewController.swift
  ownCloud/Client/Viewer/PDF/PDFViewerViewController.swift
  ownCloud/Client/Viewer/QuickLook/PreviewViewController.swift
  ownCloud/Client/Viewer/WebView/WebViewDisplayViewController.swift
  ownCloud/Resources/de.lproj/Localizable.strings
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Tools/DisplaySleepPreventer.swift
  ownCloudAppShared/Client/Actions/Action.swift
Labels: Approved by QA

#926 [fix/passcode-settings-ui-update] Passcode Settings UI Update
  CHANGELOG.md
  changelog/unreleased/923
  ownCloud/Settings/SecuritySettingsSection.swift
  ownCloudAppShared/AppLock/PasscodeSetupCoordinator.swift
Labels: Approved by QA

#929 [fix/japanese-input-support] Japanese Input Support
  CHANGELOG.md
  changelog/unreleased/916
  ownCloudAppShared/User Interface/StaticTableView/StaticTableViewRow.swift
Labels: Approved by QA

#931 [DOCS] IOS Docs Improvement
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/index.adoc
  docs/modules/ROOT/pages/ios_accounts.adoc
  docs/modules/ROOT/pages/ios_available_offline.adoc
  docs/modules/ROOT/pages/ios_collaboration.adoc
  docs/modules/ROOT/pages/ios_faq.adoc
  docs/modules/ROOT/pages/ios_files.adoc
  docs/modules/ROOT/pages/ios_files_integration.adoc
  docs/modules/ROOT/pages/ios_installation.adoc
  docs/modules/ROOT/pages/ios_mdm.adoc
  docs/modules/ROOT/pages/ios_quick_access.adoc
  docs/modules/ROOT/pages/ios_security.adoc
  docs/modules/ROOT/pages/ios_settings.adoc
  docs/modules/ROOT/pages/ios_task_scheduling.adoc
  docs/modules/ROOT/pages/ios_troubleshooting.adoc
  docs/yarn.lock
Labels: documentation

#932 [fix/qlpreview-dark-mode] Dark Mode Support for QLPreviewController
  CHANGELOG.md
  changelog/unreleased/919
  ownCloud/Client/Viewer/DisplayViewController.swift
  ownCloud/Client/Viewer/QuickLook/PreviewViewController.swift
Labels: Approved by QA
