Repository owncloud/ios-app, pull requests merged in 2021-02, with the labels that each got.

#853 [iOS 14] New photo picker / permissions model
  ownCloud/Client/Actions/Actions+Extensions/UploadMediaAction.swift
  ownCloud/Resources/Info.plist
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloudAppFramework/Licensing/Providers/App Store/OCLicenseAppStoreProvider.m
Labels: Approved by QA, enhancement

#874 [feature/new-issue-view] New Issue view / presentation
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/Bookmarks/BookmarkViewController.swift
  ownCloud/Bookmarks/Issues/Issues Animators/IssuesDismissalAnimator.swift
  ownCloud/Bookmarks/Issues/Issues Animators/IssuesPresentationAnimator.swift
  ownCloud/Bookmarks/Issues/Issues Subclasses/CertificateViewController.swift
  ownCloud/Bookmarks/Issues/Issues Subclasses/ConnectionIssueViewController.swift
  ownCloud/Bookmarks/Issues/IssuesViewController.swift
  ownCloud/Client/Actions/Action+UserInterface.swift
  ownCloud/Client/ClientRootViewController.swift
  ownCloud/Diagnostic/DiagnosticManager.swift
  ownCloud/Import/ImportFilesController.swift
  ownCloud/Issues/IssuesCardViewController.swift
  ownCloud/Key Commands/KeyCommands.swift
  ownCloud/Licensing/Product List/LicenseInAppPurchaseFeatureView.swift
  ownCloud/Messages/AlertView.swift
  ownCloud/Migration/Migration.swift
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/SDK Extensions/OCIssue+Extension.swift
  ownCloud/Settings/Certificate Management/CertificateManagementViewController.swift
  ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
  ownCloudAppShared/User Interface/Card Presentation Controller/CardPresentationController.swift
  ownCloudAppShared/User Interface/More/FrameViewController.swift
  ownCloudAppShared/User Interface/StaticTableView/StaticTableViewRow.swift
  ownCloudAppShared/User Interface/Theme/UI/ThemeTableViewCell.swift
Labels: Approved by QA

#882 [fix/branded-login-ipad-UI] Fixed Branded UI on iPad
  ownCloud/Static Login/Interface/StaticLoginSetupViewController.swift
  ownCloud/Static Login/Interface/StaticLoginViewController.swift
  ownCloudAppShared/User Interface/Theme/NSObject+ThemeApplication.swift
Labels: Approved by QA

#850 [feature/enhanced-drag-drop] Enhanced drag & drop support
  ownCloud/Settings/LogFilesViewController.swift
  ownCloudAppShared/Client/File Lists/ClientQueryViewController.swift
Labels: AppleSilicon, Approved by QA

#884 Fixing Media Player Behaviour
  ownCloud/Client/Viewer/DisplayHostViewController.swift
  ownCloudAppShared/SDK Extensions/OCItem+Extension.swift
Labels: Approved by QA, UX

#773 MDM Enhancements
  doc/CONFIGURATION.json
  docs/modules/ROOT/pages/ios_mdm.adoc
  docs/modules/ROOT/pages/ios_mdm_tables.adoc
  enterprise/MDM/AppConfig/log-passcode-specfile.xml
  enterprise/MDM/AppConfig/specfile.xml
  ownCloud Intents/OCBookmarkManager+Extension.swift
  ownCloud.xcodeproj/project.pbxproj
  ownCloud/AppDelegate.swift
  ownCloud/Release Notes/ReleaseNotesHostViewController.swift
  ownCloud/Resources/Assets.xcassets/gear.imageset/gear.png
  ownCloud/Resources/en.lproj/Localizable.strings
  ownCloud/Server List/ServerListTableViewController.swift
  ownCloud/Settings/SecuritySettingsSection.swift
  ownCloud/Settings/SettingsViewController.swift
  ownCloudAppShared/AppLock/AppLockManager.swift
  ownCloudAppShared/AppLock/PasscodeSetupCoordinator.swift
  ownCloudAppShared/Client/Actions/Action.swift
  ownCloudAppShared/Tools/VendorServices.swift
Labels: feature:MDM

#898 Temporarily remove "Shortcuts" from MDM docs
  docs/modules/ROOT/pages/ios_mdm.adoc
Labels: documentation

#900 [fix/acknowledgement-colors] Fix legibility of Acknowledgements in dark mode
  ownCloud/Settings/MoreSettingsSection.swift
  ownCloud/UI Elements/TextViewController.swift
Labels: Approved by QA
